#!/bin/sh

#########################################

##        ENVIRONMENTAL CONFIG         ##

#########################################

#Apply the given parameters on first boot (PGID, PUID, TZ)
if [ ! -f "/etc/initialbootpassed" ]
then
	echo "-------> Initial boot"
	if [ -n "${PGID}" ]
	then
		OLDGID=$(id -g docker)
		groupmod -g $PGID docker
		find / -group $OLDGID -exec chgrp -h docker {} \;
	fi

	if [ -n "${PUID}" ]
	then
		OLDUID=$(id -u docker)
		usermod -u $PUID docker
		find / -user $OLDUID -exec chown -h docker {} \;
	fi

	if [ -n "${TZ}" ]; then echo $TZ > /etc/timezone; fi

	touch /etc/initialbootpassed
else
	echo "-------> Standard boot"
fi

#########################################

##          RUN THE SERVICES           ##

#########################################

#Launch the squeezebox server
exec squeezeboxserver --user docker --prefsdir /config/prefs --logdir /config/logs --cachedir /config/cache

